#ifndef _DRV_INTERFACE_H_
#define _DRV_INTERFACE_H_

#include "drv_interface_type.h"

#define _NDIS_CONTROL_CODE(request,method) \
	CTL_CODE(FILE_DEVICE_PHYSICAL_NETCARD, request, method, FILE_ANY_ACCESS)

#define IOCTL_FILTER_RESTART_ALL            _NDIS_CONTROL_CODE(0x00, METHOD_BUFFERED)
#define IOCTL_FILTER_RESTART_ONE_INSTANCE   _NDIS_CONTROL_CODE(0x01, METHOD_BUFFERED)
#define IOCTL_FILTER_ENUERATE_ALL_INSTANCES _NDIS_CONTROL_CODE(0x02, METHOD_BUFFERED)
#define IOCTL_FILTER_QUERY_ALL_STAT         _NDIS_CONTROL_CODE(0x03, METHOD_BUFFERED)
#define IOCTL_FILTER_CLEAR_ALL_STAT         _NDIS_CONTROL_CODE(0x04, METHOD_BUFFERED)
#define IOCTL_FILTER_SET_OID_VALUE          _NDIS_CONTROL_CODE(0x05, METHOD_BUFFERED)
#define IOCTL_FILTER_QUERY_OID_VALUE        _NDIS_CONTROL_CODE(0x06, METHOD_BUFFERED)
#define IOCTL_FILTER_CANCEL_REQUEST         _NDIS_CONTROL_CODE(0x07, METHOD_BUFFERED)
#define IOCTL_FILTER_READ_DRIVER_CONFIG     _NDIS_CONTROL_CODE(0x08, METHOD_BUFFERED)
#define IOCTL_FILTER_WRITE_DRIVER_CONFIG    _NDIS_CONTROL_CODE(0x09, METHOD_BUFFERED)
#define IOCTL_FILTER_READ_ADAPTER_CONFIG    _NDIS_CONTROL_CODE(0x0A, METHOD_BUFFERED)
#define IOCTL_FILTER_WRITE_ADAPTER_CONFIG   _NDIS_CONTROL_CODE(0x0B, METHOD_BUFFERED)
#define IOCTL_FILTER_READ_INSTANCE_CONFIG   _NDIS_CONTROL_CODE(0x0C, METHOD_BUFFERED)
#define IOCTL_FILTER_WRITE_INSTANCE_CONFIG  _NDIS_CONTROL_CODE(0x0D, METHOD_BUFFERED)

//添加代码
//获取所有的网卡接口序号
#define IOCTL_LOADER_ALL_APP_MODULE			_NDIS_CONTROL_CODE(0x20, METHOD_BUFFERED)
//input NET_LUID                     miniport_net_luid;
//LCXL_IP
//设置虚拟IP
#define IOCTL_LOADER_SET_VIRTUAL_IP			_NDIS_CONTROL_CODE(0x22, METHOD_BUFFERED)
//LCXL_IP
//获取服务器列表
//input APP_IP
//output APP_SERVER_LIST
#define IOCTL_LOADER_GET_SERVER_LIST		_NDIS_CONTROL_CODE(0x23, METHOD_BUFFERED)
//添加服务器
//input APP_ADD_SERVER
#define IOCTL_LOADER_ADD_SERVER				_NDIS_CONTROL_CODE(0x24, METHOD_BUFFERED)
//删除服务器
//input APP_DEL_SERVER
#define IOCTL_LOADER_DEL_SERVER				_NDIS_CONTROL_CODE(0x25, METHOD_BUFFERED)
//!添加代码!

#endif